# Generated by Django 5.1.3 on 2024-12-03 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('folio', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('monto', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fono', models.PositiveIntegerField()),
                ('FonoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_fono_cliente', to='cliente.cliente')),
                ('FonoEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_fono_empleado', to='empleado.empleado')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
            options={
                'db_table': 'Boleta',
            },
        ),
    ]
