# Generated by Django 3.1.12 on 2024-12-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehiculo',
            table='Vehiculo',
        ),
    ]
