# Generated by Django 3.1.12 on 2024-12-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_cliente_usuario'),
        ('vehiculo', '0003_auto_20241202_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='marca',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='dueño',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='year',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='id',
            field=models.AutoField(auto_created=True, default='Sin descripción', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio',
            field=models.PositiveIntegerField(default='Sin descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='vehiculo',
            table=None,
        ),
    ]
