# Generated by Django 3.1.12 on 2024-12-02 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_cliente_usuario'),
        ('vehiculo', '0004_auto_20241202_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='patente',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='año',
            field=models.PositiveIntegerField(default='sin descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='sin descripcion', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripción', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
