# Generated by Django 3.1.12 on 2024-12-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
